#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=80

USE_PROCD=1

G_OPTS="daemon off;"

NGINX_UTIL="/usr/bin/nginx-util"

[ -f "${NGINX_UTIL}" ] && eval $("${NGINX_UTIL}" get_env)

CONF=""

nginx_init() {
	[ -z "${CONF}" ] || return # already called.

	[ -d /var/log/nginx ] || mkdir -p /var/log/nginx
	[ -d /var/lib/nginx ] || mkdir -p /var/lib/nginx
	chown -R nobody:nogroup /var/lib/nginx

	${NGINX_UTIL} init_lan

	CONF="${NGINX_CONF}"

	local message
	message="$(/usr/sbin/nginx -t -c "${CONF}" -g "${G_OPTS}" 2>&1)" ||
	{
		echo -e "${message}" | logger -t "nginx_init" -p "daemon.err"
		logger -s -t "nginx_init" -p "daemon.err" "NOT using conf file!"
		echo "show config to be used by: nginx -T -c '${CONF}'" >&2
		exit 1
	}

	logger -t "nginx_init" -p "daemon.info" "using ${CONF} (the test is ok)"
}

add_mdns() {
	local cfg="$1"
	local port enabled service

	config_get enabled "$cfg" enabled
	config_get port "$cfg" listen

	port=$(echo "$port" | head -n1 | awk '{print $1;}')


	if [ "$enabled" != "0" ] && [ "$enabled" != "false" ] && [ -n "$port" ]; then
		case "$port" in
			"80")
				service="http"
				;;
			"8080")
				service="http-alt"
				;;
			"443")
				service="https"
				;;
			"8443")
				service="pcsync-https"
				;;
			*)
				service="custom-http-$port"
				;;
		esac

		procd_add_mdns_service "$service" "tcp" "$port" "daemon=nginx"
	fi
}

configure_mdns() {
	local mdns="$(uci -q get nginx.global.mdns)"

	if [ "$mdns" = "1" ] || [ "$mdns" = "true" ]; then
		procd_open_data
		json_add_object "mdns"

		config_load nginx
		config_foreach add_mdns server

		json_close_object
		procd_close_data
	fi
}

start_service() {
	nginx_init

	procd_open_instance
	procd_set_param command /usr/sbin/nginx -c "${CONF}" -g "${G_OPTS}"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file "${CONF}" "${CONF_DIR}*.conf" "${CONF_DIR/conf.d/snippets}*.conf"
	procd_set_param respawn

	configure_mdns

	procd_close_instance
}


reload_service() {
	nginx_init

	if [ "$(cat "/proc/$(cat "/var/run/nginx.pid")/cmdline")" = \
	     "nginx: master process /usr/sbin/nginx -c ${CONF} -g ${G_OPTS}" ]
	then procd_send_signal nginx
	else restart
	fi
}


service_triggers() {
	procd_add_reload_interface_trigger loopback
	procd_add_reload_interface_trigger lan
}


extra_command "relog" "Reopen log files (without reloading)"
relog() {
	[ -d /var/log/nginx ] || mkdir -p /var/log/nginx
	procd_send_signal nginx '*' USR1
}
